"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class DisplayBytesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    DATA_FIELD_NUMBER: builtins.int
    name: builtins.str
    data: builtins.bytes
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        data: builtins.bytes = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["data", b"data", "name", b"name"]) -> None: ...

global___DisplayBytesRequest = DisplayBytesRequest

@typing_extensions.final
class DisplayBytesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DisplayBytesResponse = DisplayBytesResponse

@typing_extensions.final
class WriteStringRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    XLOC_FIELD_NUMBER: builtins.int
    YLOC_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    name: builtins.str
    xloc: builtins.int
    yloc: builtins.int
    text: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        xloc: builtins.int = ...,
        yloc: builtins.int = ...,
        text: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "text", b"text", "xloc", b"xloc", "yloc", b"yloc"]) -> None: ...

global___WriteStringRequest = WriteStringRequest

@typing_extensions.final
class WriteStringResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WriteStringResponse = WriteStringResponse

@typing_extensions.final
class DrawLineRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    X1_FIELD_NUMBER: builtins.int
    Y1_FIELD_NUMBER: builtins.int
    X2_FIELD_NUMBER: builtins.int
    Y2_FIELD_NUMBER: builtins.int
    name: builtins.str
    x1: builtins.int
    y1: builtins.int
    x2: builtins.int
    y2: builtins.int
    def __init__(
        self,
        *,
        name: builtins.str = ...,
        x1: builtins.int = ...,
        y1: builtins.int = ...,
        x2: builtins.int = ...,
        y2: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name", "x1", b"x1", "x2", b"x2", "y1", b"y1", "y2", b"y2"]) -> None: ...

global___DrawLineRequest = DrawLineRequest

@typing_extensions.final
class DrawLineResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___DrawLineResponse = DrawLineResponse

@typing_extensions.final
class ResetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    name: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["name", b"name"]) -> None: ...

global___ResetRequest = ResetRequest

@typing_extensions.final
class ResetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ResetResponse = ResetResponse
