# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: display.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rdisplay.proto\x12\x1dviamlabs.component.display.v1\x1a\x1cgoogle/api/annotations.proto\"=\n\x13\x44isplayBytesRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04\x64\x61ta\x18\x02 \x01(\x0cR\x04\x64\x61ta\"\x16\n\x14\x44isplayBytesResponse\"d\n\x12WriteStringRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n\x04xloc\x18\x02 \x01(\x05R\x04xloc\x12\x12\n\x04yloc\x18\x03 \x01(\x05R\x04yloc\x12\x12\n\x04text\x18\x04 \x01(\tR\x04text\"\x15\n\x13WriteStringResponse\"e\n\x0f\x44rawLineRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n\x02x1\x18\x02 \x01(\x05R\x02x1\x12\x0e\n\x02y1\x18\x03 \x01(\x05R\x02y1\x12\x0e\n\x02x2\x18\x04 \x01(\x05R\x02x2\x12\x0e\n\x02y2\x18\x05 \x01(\x05R\x02y2\"\x12\n\x10\x44rawLineResponse\"\"\n\x0cResetRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"\x0f\n\rResetResponse2\xbb\x05\n\x0e\x44isplayService\x12\xb4\x01\n\x0c\x44isplayBytes\x12\x32.viamlabs.component.display.v1.DisplayBytesRequest\x1a\x33.viamlabs.component.display.v1.DisplayBytesResponse\";\x82\xd3\xe4\x93\x02\x35\"3/acme/api/v1/component/display/{name}/display_bytes\x12\xb0\x01\n\x0bWriteString\x12\x31.viamlabs.component.display.v1.WriteStringRequest\x1a\x32.viamlabs.component.display.v1.WriteStringResponse\":\x82\xd3\xe4\x93\x02\x34\"2/acme/api/v1/component/display/{name}/write_string\x12\xa4\x01\n\x08\x44rawLine\x12..viamlabs.component.display.v1.DrawLineRequest\x1a/.viamlabs.component.display.v1.DrawLineResponse\"7\x82\xd3\xe4\x93\x02\x31\"//acme/api/v1/component/display/{name}/draw_line\x12\x97\x01\n\x05Reset\x12+.viamlabs.component.display.v1.ResetRequest\x1a,.viamlabs.component.display.v1.ResetResponse\"3\x82\xd3\xe4\x93\x02-\"+/acme/api/v1/component/display/{name}/resetB4Z2github.com/viam-labs/display-api/src/proto/displayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'display_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/viam-labs/display-api/src/proto/display'
  _DISPLAYSERVICE.methods_by_name['DisplayBytes']._options = None
  _DISPLAYSERVICE.methods_by_name['DisplayBytes']._serialized_options = b'\202\323\344\223\0025\"3/acme/api/v1/component/display/{name}/display_bytes'
  _DISPLAYSERVICE.methods_by_name['WriteString']._options = None
  _DISPLAYSERVICE.methods_by_name['WriteString']._serialized_options = b'\202\323\344\223\0024\"2/acme/api/v1/component/display/{name}/write_string'
  _DISPLAYSERVICE.methods_by_name['DrawLine']._options = None
  _DISPLAYSERVICE.methods_by_name['DrawLine']._serialized_options = b'\202\323\344\223\0021\"//acme/api/v1/component/display/{name}/draw_line'
  _DISPLAYSERVICE.methods_by_name['Reset']._options = None
  _DISPLAYSERVICE.methods_by_name['Reset']._serialized_options = b'\202\323\344\223\002-\"+/acme/api/v1/component/display/{name}/reset'
  _globals['_DISPLAYBYTESREQUEST']._serialized_start=78
  _globals['_DISPLAYBYTESREQUEST']._serialized_end=139
  _globals['_DISPLAYBYTESRESPONSE']._serialized_start=141
  _globals['_DISPLAYBYTESRESPONSE']._serialized_end=163
  _globals['_WRITESTRINGREQUEST']._serialized_start=165
  _globals['_WRITESTRINGREQUEST']._serialized_end=265
  _globals['_WRITESTRINGRESPONSE']._serialized_start=267
  _globals['_WRITESTRINGRESPONSE']._serialized_end=288
  _globals['_DRAWLINEREQUEST']._serialized_start=290
  _globals['_DRAWLINEREQUEST']._serialized_end=391
  _globals['_DRAWLINERESPONSE']._serialized_start=393
  _globals['_DRAWLINERESPONSE']._serialized_end=411
  _globals['_RESETREQUEST']._serialized_start=413
  _globals['_RESETREQUEST']._serialized_end=447
  _globals['_RESETRESPONSE']._serialized_start=449
  _globals['_RESETRESPONSE']._serialized_end=464
  _globals['_DISPLAYSERVICE']._serialized_start=467
  _globals['_DISPLAYSERVICE']._serialized_end=1166
# @@protoc_insertion_point(module_scope)
